// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_1 from 'D:/MultiConnect Horizon/Todo-App/src/models/tasks';

export const models = {
model_1: { namespace: 'tasks', model: model_1 },
} as const
